### ISSUE TITLE
Redundant mutex

### ISSUE THREAD

**Issue by cdhowie** [nathan-fiscaletti/tokenbucket-rs#1]
https://github.com/nathan-fiscaletti/tokenbucket-rs/blob/master/src/lib.rs#L141

This mutex is redundant for a few reasons.

- The method receives `&mut self`, so access is already exclusive. This method already cannot be called concurrently without UB.
- The mutex does not protect any data, so even if the receiver type was changed to `&self` it will not compile because `self.tokens` etc. are not contained within the mutex; having the mutex will not permit writes to these fields.

In Rust, seeing a mutex guard that is not used is a huge red flag, as a mutex only serves to provide thread-safe interior mutability to the data it owns.

In my opinion, the mutex should simply be removed. It does not accomplish anything except to waste resources; the caller can protect the whole bucket with a mutex if they desire.

**Comment by nathan-fiscaletti** [comment]
Sorry I took so long to get this merged in. It somehow slipped by in my notification feed. This project was my first time working in Rust, so thank you for pointing this out. Your suggested changes have been merged and deployed in the latest version of the package.
